# https://stackoverflow.com/questions/69115729/neterr-name-not-resolved-docker
services:
  web:
    build:
      context: ./src/web
      args:
        - NODE_ENV=development
        - API_URL=http://localhost:5000/todos/v1
    environment:
      - NODE_ENV=development
    ports:
      - 80:8080
    restart: always
    networks:
      - client-side
    volumes:
      - ./src/web/src:/code/src:ro
    depends_on:
      - api
  api:
    build: ./src/Api
    ports:
      - 5000:80
    environment:
      - Configuration=Release
      - PG_DBNAME=postgres
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PASSWORD=mysecretpassword
    networks:
      - client-side
      - server-side
    healthcheck:
      test: /healthchecks/curl.sh
      interval: "15s"
    volumes:
      - ./healthchecks:/healthchecks
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      - server-side
    ports:
      - 5432:5432
    healthcheck:
      test: /healthchecks/postgres.sh
      interval: "15s"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./healthchecks:/healthchecks
networks:
  client-side: {}
  server-side: {}

volumes:
  backend-cache: {}
  db-data: {}
