# https://stackoverflow.com/questions/69115729/neterr-name-not-resolved-docker
services:
  frontend:
    build:
      context: ./src/Frontend
    environment:
      - REACT_APP_API_URL=http://localhost:5000/todos/v1
    networks:
      - client-side
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./src/Frontend/src:/code/src:ro
    depends_on:
      - api
  api:
    build: ./src/Api
    ports:
      - 5000:80
    environment:
      - Configuration=Release
      - PG_DBNAME=postgres
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PASSWORD=mysecretpassword
    networks:
      - client-side
      - server-side
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      - server-side
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  client-side: {}
  server-side: {}

volumes:
  backend-cache: {}
  db-data: {}