services:
  web:
    build:
      context: ./src/web
      args:
        ## https://stackoverflow.com/questions/69115729/neterr-name-not-resolved-docker
        ## API_URL: "http://api:80/todos/v1"
        API_URL: "http://localhost:5000/todos/v1"
    container_name: web
    environment:
      - NODE_ENV=development
    ports:
      - 3000:80
    restart: always
    networks:
      - client-side
    volumes:
      - ./src/web/src:/code/src:ro
    depends_on:
      - api
  scrapper:
    build:
      context: ./src/scrapper
    container_name: scrapper
    networks:
      - server-side
    environment:
      - API_PORT=80
      - HOST=api
    depends_on:
      api:
        condition: service_healthy
  api:
    build: ./src/Api
    container_name: api
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Configuration=Release
      - CONNECTION_STRING=Host=db;Database=lipsum-api;Username=postgres;Password=mysecretpassword;
    networks:
      - client-side
      - server-side
    healthcheck:
      test: /healthchecks/curl.sh
      interval: "15s"
    volumes:
      - ./healthchecks:/healthchecks
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:12-alpine
    restart: always
    container_name: db
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=lipsum-api
    networks:
      - server-side
    ports:
      - 5432:5432
    healthcheck:
      test: /healthchecks/postgres.sh
      interval: "15s"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./healthchecks:/healthchecks

networks:
  client-side: {}
  server-side: {}

volumes:
  backend-cache: {}
  db-data: {}
