name: Node.js-ci

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - '**.js'
            - 'src/web/**'
    pull_request:
        branches:
            - main
        paths:
            - '**.js'
            - 'src/web/**'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: 14

            - name: Install dependencies
              run: npm ci

            - name: Run tests
              run: npm test